@startuml
!include /sessions/amazing-cool-carson/mnt/07_UML-Diagramme/PlantUMLs/theme.puml
left to right direction

actor Kunde

rectangle "Online-Shop" {
  usecase "Bestellung aufgeben" as UC1
  usecase "Bezahlen" as UC2
}

Kunde --> UC1
UC1 .> UC2 : <<include>>
@enduml
