@startuml
!include /sessions/amazing-cool-carson/mnt/07_UML-Diagramme/PlantUMLs/theme.puml
class Kurs {
  -titel: String
  -schueler: List<Schueler>
  +schuelerHinzufuegen(schueler: Schueler): void
}
class Schueler {
  -name: String
}
Kurs o-- Schueler : hat
@enduml
