@startuml
!include /sessions/amazing-cool-carson/mnt/07_UML-Diagramme/PlantUMLs/theme.puml
class Bibliothekar {
  -name: String
  +buchAusleihen(buch: Buch): void
}
class Buch {
  -titel: String
  -isbn: String
}
Bibliothekar --> Buch : verwaltet
@enduml
