@startuml
!include /sessions/amazing-cool-carson/mnt/07_UML-Diagramme/diagramm-quellen/theme.puml
class Kurs {
  -titel: String
  -maxTeilnehmer: int
  -gebuehr: double
  +anmelden(s: Schüler): boolean
  +getFreiePlaetze(): int
}
@enduml
