@startuml
!include /sessions/amazing-cool-carson/mnt/07_UML-Diagramme/diagramm-quellen/theme.puml
abstract class Person {
  -name: String
  -geburtsdatum: Date
}
class Schüler {
  -matrikelnr: String
}
class Lehrer {
  -personalnr: String
}
class Kurs {
  -titel: String
  -maxTeilnehmer: int
  -gebuehr: double
  +anmelden(s: Schüler): boolean
  +getFreiePlaetze(): int
}
Lehrer "1" --> "0..*" Kurs : leitet >
Person <|-- Schüler
Person <|-- Lehrer
@enduml
