@startuml
!include /sessions/amazing-cool-carson/mnt/07_UML-Diagramme/diagramm-quellen/theme.puml
class Kunde {
  -kundennummer: String
  -name: String
  -konten: List<Konto>
  +kontoHinzufuegen(kontonummer: String): Konto
  +kontenAnzeigen(): void
}
class Konto {
  -kontonummer: String
  -kunde: Kunde
}
Kunde "1" o-- "1..*" Konto : hat
@enduml
