@startuml
!include /sessions/amazing-cool-carson/mnt/07_UML-Diagramme/PlantUMLs/theme.puml
[*] --> Eingegangen

Eingegangen --> InPruefung : pruefungStarten()
InPruefung --> Angenommen : annehmen()
InPruefung --> Abgelehnt : ablehnen()

Angenommen --> [*]
Abgelehnt --> [*]
@enduml
