@startuml
!include /sessions/amazing-cool-carson/mnt/07_UML-Diagramme/diagramm-quellen/theme.puml
left to right direction

actor Kunde

rectangle "Geldautomat-System" {
  usecase "Geld abheben" as UC1
  usecase "Kontostand abfragen" as UC2
  usecase "Authentifizieren" as UC3
}

Kunde --> UC1
Kunde --> UC2

UC1 .> UC3 : <<include>>
UC2 .> UC3 : <<include>>
@enduml
