@startuml
!include /sessions/amazing-cool-carson/mnt/07_UML-Diagramme/diagramm-quellen/theme.puml
left to right direction

actor Kunde

rectangle "Ticketsystem" {
  usecase "Ticket kaufen" as UC1
  usecase "Rabattcode eingeben" as UC2
}

Kunde --> UC1

UC2 .> UC1 : <<extend>>
@enduml
