@startuml
!include /sessions/amazing-cool-carson/mnt/07_UML-Diagramme/diagramm-quellen/theme.puml
left to right direction
usecase "Geld abheben" as UC1
usecase "Authentifizieren" as UC2
UC1 .> UC2 : <<include>>
@enduml
