@startuml
!include /sessions/amazing-cool-carson/mnt/07_UML-Diagramme/PlantUMLs/theme.puml
skinparam ActivityStartColor black
skinparam ActivityEndColor black
skinparam ActivityBackgroundColor #E3F2FD
skinparam ActivityBorderColor #1976D2
skinparam ActivityFontColor #0D47A1
skinparam ActivityBarColor black
!pragma useVerticalIf on

start
:Auto aufschließen;
fork
  :Motor prüfen;
fork again
  :Reifendruck prüfen;
end fork
:Motor starten;
:Losfahren;
stop
@enduml
