@startuml
!include /sessions/amazing-cool-carson/mnt/07_UML-Diagramme/diagramm-quellen/theme.puml
state NichtVerifiziert
state Aktiv
state Gesperrt

NichtVerifiziert --> Aktiv : verifizieren()
Aktiv --> Gesperrt : sperren()
@enduml