@startuml
!include /sessions/amazing-cool-carson/mnt/07_UML-Diagramme/diagramm-quellen/theme.puml
state Aktiv {
}
Aktiv : entry / Willkommens-E-Mail senden
Aktiv : exit / Abmelde-E-Mail senden

state NichtVerifiziert
state Deaktiviert

NichtVerifiziert --> Aktiv : verifizieren()
Deaktiviert --> Aktiv : aktivieren()
Aktiv --> Deaktiviert : deaktivieren()
@enduml